// Catalogo unico de campos de configuracao (plano §11; decisao D1).
// Fonte unica de verdade: schemas.js compoe os schemas Zod a partir daqui e
// environment-source.js implementa a leitura. Nenhuma lista paralela.
//
// Kinds reproduzem EXATAMENTE a semantica atual de src/config.js (loadConfig)
// e de bin/tc-broker.js, incluindo peculiaridades historicas (ver uintQuirk e
// boolString). Campos derivados (pathSeparator) e campos de conexao do agente
// lidos por bin/tc-agent.js sao documentados aqui com inCompose:false.
//
// Sensibilidade:
//   secret    -> nunca sai em snapshot/diff/auditoria; apenas status
//   sensitive -> valor exibido (paths, usuarios), marcado como sensivel
//   normal    -> valor exibido
//
// Aplicacao (plano §6.5):
//   hot       -> pode substituir estado imutavel apos testes (D5: tratado como
//                restart ate existirem testes de hot reload concorrente)
//   reconnect -> exige reconstruir a conexao reversa
//   restart   -> exige reiniciar o processo
//   external  -> controlado por variavel de ambiente, servico ou secret manager

import path from "node:path";

const normal = "normal";
const sensitive = "sensitive";
const secret = "secret";

const hot = "hot";
const reconnect = "reconnect";
const restart = "restart";
const external = "external";

function defaultPath(...segments) {
	return path.join(...segments);
}

// ---------------------------------------------------------------------------
// Agente (superficie de loadConfig + campos de conexao lidos por tc-agent)
// ---------------------------------------------------------------------------
// Ordem importa: allowTeamcenterRead precede os soaFlag que herdam dele e
// composeFromSources resolve na ordem do array.

export const AGENT_FIELDS = [
	{
		name: "token",
		envName: "TC_TOKEN",
		cliFlag: "token",
		kind: "string",
		sensitivity: secret,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "host",
		envName: "TC_HOST",
		cliFlag: "host",
		kind: "string",
		default: "127.0.0.1",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "port",
		envName: "TC_PORT",
		cliFlag: "port",
		kind: "numberFromString",
		default: 4100,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "allowWrite",
		envName: "TC_ALLOW_WRITE",
		cliFlag: "allowWrite",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowDiagnostics",
		envName: "TC_ALLOW_DIAGNOSTICS",
		cliFlag: "allowDiagnostics",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowDbDiagnostics",
		envName: "TC_ALLOW_DB_DIAGNOSTICS",
		cliFlag: "allowDbDiagnostics",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	// Master switch SOA: deve ser resolvido antes dos soaFlag que herdam dele.
	{
		name: "allowTeamcenterRead",
		envName: "TC_ALLOW_TEAMCENTER_READ",
		cliFlag: "allowTeamcenterRead",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaPreflight",
		envName: "TC_ALLOW_TEAMCENTER_SOA_PREFLIGHT",
		cliFlag: "allowTeamcenterSoaPreflight",
		kind: "soaFlag",
		fallbackField: "allowTeamcenterRead",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaHealth",
		envName: "TC_ALLOW_TEAMCENTER_SOA_HEALTH",
		cliFlag: "allowTeamcenterSoaHealth",
		kind: "soaFlag",
		fallbackField: "allowTeamcenterRead",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaPreferences",
		envName: "TC_ALLOW_TEAMCENTER_SOA_PREFERENCES",
		cliFlag: "allowTeamcenterSoaPreferences",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaObjects",
		envName: "TC_ALLOW_TEAMCENTER_SOA_OBJECTS",
		cliFlag: "allowTeamcenterSoaObjects",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaQueries",
		envName: "TC_ALLOW_TEAMCENTER_SOA_QUERIES",
		cliFlag: "allowTeamcenterSoaQueries",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaDatasets",
		envName: "TC_TEAMCENTER_SOA_DATASETS",
		cliFlag: "allowTeamcenterSoaDatasets",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowTeamcenterSoaFms",
		envName: "TC_TEAMCENTER_SOA_FMS",
		cliFlag: "allowTeamcenterSoaFms",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowBrowserDiagnostics",
		envName: "TC_ALLOW_BROWSER_DIAGNOSTICS",
		cliFlag: "allowBrowserDiagnostics",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowLogRead",
		envName: "TC_ALLOW_LOG_READ",
		cliFlag: "allowLogRead",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "allowCapabilityTasks",
		envName: "TC_ALLOW_CAPABILITY_TASKS",
		cliFlag: "allowCapabilityTasks",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "enforceCapabilities",
		envName: "TC_ENFORCE_CAPABILITIES",
		cliFlag: "enforceCapabilities",
		kind: "bool",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "agentId",
		envName: "TC_AGENT_ID",
		cliFlag: "agentId",
		kind: "string",
		sensitivity: normal,
		applyImpact: reconnect,
		mutableInUi: true,
	},
	{
		name: "agentResultBufferCapacity",
		envName: "TC_AGENT_RESULT_BUFFER_CAPACITY",
		cliFlag: "agentResultBufferCapacity",
		kind: "uint",
		errorName: "TC_AGENT_RESULT_BUFFER_CAPACITY",
		default: 100,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "capabilityPublicKey",
		envName: "TC_CAPABILITY_PUBLIC_KEY",
		cliFlag: "capabilityPublicKey",
		kind: "string",
		sensitivity: secret,
		applyImpact: restart,
		mutableInUi: false,
		note: "material criptografico (PEM): apenas status na UI (plano §17)",
	},
	{
		name: "capabilityIssuer",
		envName: "TC_CAPABILITY_ISSUER",
		cliFlag: "capabilityIssuer",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
		note: "issuer confiavel do agente; definido pelo broker na homologacao",
	},
	{
		name: "auditLogPath",
		envName: "TC_AUDIT_LOG_PATH",
		cliFlag: "auditLogPath",
		kind: "string",
		default: () => defaultPath(".", "logs", "tc-agent-audit.jsonl"),
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "browserDevtoolsUrl",
		envName: "TC_BROWSER_DEVTOOLS_URL",
		cliFlag: "browserDevtoolsUrl",
		kind: "string",
		default: "http://127.0.0.1:9222",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterLogDir",
		envName: "TC_TEAMCENTER_LOG_DIR",
		cliFlag: "teamcenterLogDir",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterUrl",
		envName: "TC_TEAMCENTER_URL",
		cliFlag: "teamcenterUrl",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterUser",
		envName: "TC_TEAMCENTER_USER",
		cliFlag: "teamcenterUser",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterPassword",
		envName: "TC_TEAMCENTER_PASSWORD",
		cliFlag: "teamcenterPassword",
		kind: "string",
		sensitivity: secret,
		applyImpact: restart,
		mutableInUi: true,
		note: "write-only; arquivo gerenciado aceita apenas secretRef",
	},
	{
		name: "teamcenterGroup",
		envName: "TC_TEAMCENTER_GROUP",
		cliFlag: "teamcenterGroup",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "teamcenterRole",
		envName: "TC_TEAMCENTER_ROLE",
		cliFlag: "teamcenterRole",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "teamcenterLocale",
		envName: "TC_TEAMCENTER_LOCALE",
		cliFlag: "teamcenterLocale",
		kind: "string",
		default: "en_US",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "teamcenterJava",
		envName: "TC_TEAMCENTER_JAVA",
		cliFlag: "teamcenterJava",
		kind: "string",
		default: "java",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaAdapterJar",
		envName: "TC_TEAMCENTER_SOA_ADAPTER_JAR",
		cliFlag: "teamcenterSoaAdapterJar",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaLib",
		envName: "TC_TEAMCENTER_SOA_LIB",
		cliFlag: "teamcenterSoaLib",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaExtraJars",
		envName: "TC_TEAMCENTER_SOA_EXTRA_JARS",
		cliFlag: "teamcenterSoaExtraJars",
		kind: "list",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaPolicyFile",
		envName: "TC_TEAMCENTER_SOA_POLICY_FILE",
		cliFlag: "teamcenterSoaPolicyFile",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "environmentRegistryFile",
		envName: "TC_ENVIRONMENT_REGISTRY_FILE",
		cliFlag: "environmentRegistryFile",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: false,
		note: "registro carregado na inicializacao (src/environments/registry.js)",
	},
	{
		name: "teamcenterSoaMaxConcurrency",
		envName: "TC_TEAMCENTER_SOA_MAX_CONCURRENCY",
		cliFlag: "teamcenterSoaMaxConcurrency",
		kind: "uint",
		errorName: "TC_TEAMCENTER_SOA_MAX_CONCURRENCY",
		default: 1,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaQueueLimit",
		envName: "TC_TEAMCENTER_SOA_QUEUE_LIMIT",
		cliFlag: "teamcenterSoaQueueLimit",
		kind: "uint",
		errorName: "TC_TEAMCENTER_SOA_QUEUE_LIMIT",
		default: 4,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaRateLimit",
		envName: "TC_TEAMCENTER_SOA_RATE_LIMIT",
		cliFlag: "teamcenterSoaRateLimit",
		kind: "uint",
		errorName: "TC_TEAMCENTER_SOA_RATE_LIMIT",
		default: 30,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaTimeoutMs",
		envName: "TC_TEAMCENTER_SOA_TIMEOUT_MS",
		cliFlag: "teamcenterSoaTimeoutMs",
		kind: "uint",
		errorName: "TC_TEAMCENTER_SOA_TIMEOUT_MS",
		default: 30_000,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaRequireTls",
		envName: "TC_TEAMCENTER_SOA_REQUIRE_TLS",
		cliFlag: "teamcenterSoaRequireTls",
		kind: "soaFlag",
		default: false,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "teamcenterSoaTrustStore",
		envName: "TC_TEAMCENTER_SOA_TRUST_STORE",
		cliFlag: "teamcenterSoaTrustStore",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	// Campos derivados: nao sao gerenciaveis, apenas compostos (shape do loadConfig).
	{
		name: "pathSeparator",
		kind: "derived",
		derive: () => (process.platform === "win32" ? ";" : ":"),
		sensitivity: normal,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "dbServer",
		envName: "TC_DB_SERVER",
		cliFlag: "dbServer",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbPort",
		envName: "TC_DB_PORT",
		cliFlag: "dbPort",
		kind: "optionalPort",
		errorName: "TC_DB_PORT",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbName",
		envName: "TC_DB_NAME",
		cliFlag: "dbName",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbUser",
		envName: "TC_DB_USER",
		cliFlag: "dbUser",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbPassword",
		envName: "TC_DB_PASSWORD",
		cliFlag: "dbPassword",
		kind: "string",
		sensitivity: secret,
		applyImpact: restart,
		mutableInUi: true,
		note: "write-only; arquivo gerenciado aceita apenas secretRef",
	},
	{
		name: "dbEncrypt",
		envName: "TC_DB_ENCRYPT",
		cliFlag: "dbEncrypt",
		kind: "boolString",
		default: "true",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbTrustServerCertificate",
		envName: "TC_DB_TRUST_SERVER_CERTIFICATE",
		cliFlag: "dbTrustServerCertificate",
		kind: "boolStringTrue",
		default: "false",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "dbConnectTimeoutMs",
		envName: "TC_DB_CONNECT_TIMEOUT_MS",
		cliFlag: "dbConnectTimeoutMs",
		kind: "uint",
		errorName: "TC_DB_CONNECT_TIMEOUT_MS",
		default: 10_000,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	// Peculiaridade historica: loadConfig chama positiveNumber(value, 30_000)
	// com apenas dois argumentos; mantemos a chamada (e a mensagem de erro
	// "30000 deve ser um inteiro entre 1 e 120000") para compatibilidade.
	{
		name: "dbRequestTimeoutMs",
		envName: "TC_DB_REQUEST_TIMEOUT_MS",
		cliFlag: "dbRequestTimeoutMs",
		kind: "uintQuirk",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "diagnosticHosts",
		envName: "TC_DIAGNOSTIC_HOSTS",
		cliFlag: "diagnosticHosts",
		kind: "listOrDefault",
		default: ["localhost", "127.0.0.1", "::1"],
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
	},
	{
		name: "readPaths",
		envName: "TC_ALLOWED_READ_PATHS",
		cliFlag: "readPaths",
		kind: "list",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
		note: "selecao segura de paths locais (Fase 3)",
	},
	{
		name: "writePaths",
		envName: "TC_ALLOWED_WRITE_PATHS",
		cliFlag: "writePaths",
		kind: "list",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: true,
		note: "selecao segura de paths locais (Fase 3)",
	},
	{
		name: "staging",
		envName: "TC_STAGING_DIR",
		cliFlag: "staging",
		kind: "string",
		default: () => defaultPath(".", "staging"),
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "tunnel",
		envName: "TC_TUNNEL",
		cliFlag: "tunnel",
		kind: "string",
		default: "localtunnel",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "publicUrl",
		envName: "TC_PUBLIC_URL",
		cliFlag: "publicUrl",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "tunnelHost",
		envName: "TC_TUNNEL_HOST",
		cliFlag: "tunnelHost",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "cloudflaredPath",
		envName: "TC_CLOUDFLARED_PATH",
		cliFlag: "cloudflaredPath",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: false,
	},
	// Campos de conexao do agente: lidos por bin/tc-agent.js, fora de loadConfig.
	// Passam a ser gerenciados na Fase 3 (console local de edicao).
	{
		name: "brokerUrl",
		envName: "TC_BROKER_URL",
		kind: "string",
		sensitivity: normal,
		applyImpact: reconnect,
		mutableInUi: false,
		inCompose: false,
		note: "Fase 3: conexao reversa",
	},
	{
		name: "agentCertificate",
		envName: "TC_AGENT_CERTIFICATE",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: false,
		inCompose: false,
		note: "Fase 3: selecao local de path",
	},
	{
		name: "agentPrivateKey",
		envName: "TC_AGENT_PRIVATE_KEY",
		kind: "string",
		sensitivity: secret,
		applyImpact: restart,
		mutableInUi: false,
		inCompose: false,
		note: "Fase 3: status apenas, chave nunca sai",
	},
	{
		name: "brokerCa",
		envName: "TC_BROKER_CA",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: restart,
		mutableInUi: false,
		inCompose: false,
		note: "Fase 3: selecao local de path",
	},
	{
		name: "teamcenterSoaClientEncoding",
		envName: "TC_TEAMCENTER_SOA_CLIENT_ENCODING",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
		inCompose: false,
		note: "lido por teamcenter-soa.js; formulario SOA da Fase 3",
	},
];

// ---------------------------------------------------------------------------
// Broker (superficie de bin/tc-broker.js, plano §11.1)
// ---------------------------------------------------------------------------
// O entry point continua lendo process.env diretamente nesta fase; o catalogo
// documenta e o manager valida o arquivo gerenciado. Fases 4/5 rewires o bin.

export const BROKER_FIELDS = [
	{
		name: "port",
		envName: "TC_BROKER_PORT",
		kind: "numberFromString",
		default: 8443,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "tlsKey",
		envName: "TC_BROKER_TLS_KEY",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "tlsCertificate",
		envName: "TC_BROKER_TLS_CERTIFICATE",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "clientCa",
		envName: "TC_BROKER_CLIENT_CA",
		kind: "string",
		sensitivity: sensitive,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "apiPort",
		envName: "TC_BROKER_API_PORT",
		kind: "numberFromString",
		default: 8444,
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: false,
	},
	{
		name: "apiToken",
		envName: "TC_BROKER_API_TOKEN",
		kind: "string",
		sensitivity: secret,
		applyImpact: external,
		mutableInUi: false,
		note: "status apenas; token nunca sai",
	},
	{
		name: "apiTlsKey",
		envName: "TC_BROKER_API_TLS_KEY",
		kind: "string",
		fallbackField: "tlsKey",
		sensitivity: sensitive,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "apiTlsCertificate",
		envName: "TC_BROKER_API_TLS_CERTIFICATE",
		kind: "string",
		fallbackField: "tlsCertificate",
		sensitivity: sensitive,
		applyImpact: external,
		mutableInUi: false,
	},
	{
		name: "capabilityPrivateKey",
		envName: "TC_CAPABILITY_PRIVATE_KEY",
		kind: "string",
		sensitivity: secret,
		applyImpact: external,
		mutableInUi: false,
		note: "status apenas; material de assinatura nunca sai",
	},
	{
		name: "capabilityIssuer",
		envName: "TC_CAPABILITY_ISSUER",
		kind: "string",
		sensitivity: normal,
		applyImpact: restart,
		mutableInUi: true,
		note: "edicao exige reautenticacao (plano §11.1)",
	},
	{
		name: "allowedActions",
		envName: "TC_BROKER_ALLOWED_ACTIONS",
		kind: "list",
		sensitivity: normal,
		applyImpact: hot,
		mutableInUi: true,
		note: "hot reload somente apos testes de concorrencia (D5)",
	},
	{
		name: "capabilityTtlSeconds",
		envName: "TC_CAPABILITY_TTL_SECONDS",
		kind: "numberFromString",
		default: 60,
		sensitivity: normal,
		applyImpact: hot,
		mutableInUi: true,
		note: "hot reload somente apos testes de concorrencia (D5)",
	},
	{
		name: "subject",
		envName: "TC_BROKER_SUBJECT",
		kind: "string",
		default: "codex-service",
		sensitivity: normal,
		applyImpact: hot,
		mutableInUi: true,
		note: "hot reload somente apos testes de concorrencia (D5)",
	},
];

export const CATALOGS = Object.freeze({
	broker: BROKER_FIELDS,
	agent: AGENT_FIELDS,
});

export function catalogFor(target) {
	if (target !== "broker" && target !== "agent") {
		throw new Error(`target invalido: ${target}`);
	}
	return CATALOGS[target];
}
